<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-07T20:12:36 IST" name="Default suite" finished-at="2024-12-07T20:12:44 IST" duration-ms="8907">
    <groups>
    </groups>
    <test started-at="2024-12-07T20:12:36 IST" name="Default test" finished-at="2024-12-07T20:12:44 IST" duration-ms="8907">
      <class name="register.TC_RF_019">
        <test-method signature="verifyRegisterAccountUsingLeadingAndTrailingSpaces()[pri:0, instance:register.TC_RF_019@5ab956d7]" started-at="2024-12-07T20:12:36 IST" name="verifyRegisterAccountUsingLeadingAndTrailingSpaces" finished-at="2024-12-07T20:12:44 IST" duration-ms="8524" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Arun] but found [     Arun     ],
expected [Motoori] but found [     Motoori     ],
expected [1234567890] but found [     1234567890     ]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Arun] but found [     Arun     ],
expected [Motoori] but found [     Motoori     ],
expected [1234567890] but found [     1234567890     ]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at register.TC_RF_019.verifyRegisterAccountUsingLeadingAndTrailingSpaces(TC_RF_019.java:59)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyRegisterAccountUsingLeadingAndTrailingSpaces -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:register.TC_RF_019@5ab956d7]" started-at="2024-12-07T20:12:44 IST" name="teardown" finished-at="2024-12-07T20:12:44 IST" duration-ms="323" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- register.TC_RF_019 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
